<?php

declare(strict_types=1);

namespace Base\Tenant\Http\Controllers;

use Base\Tenant\Facades\Tenant;
use Base\Tenant\Files\FileCollection;
use Base\Tenant\Files\FileStore;
use Base\Tenant\Models\File;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * The upload endpoints.
 *
 * The collection is never taken from the request as a set of rules -- only as
 * a name, which is then resolved against what the owning model declares. A
 * request that could describe its own limits would be a request that could
 * lift them.
 */
class FileController extends Controller
{
    public function __construct(protected FileStore $files) {}

    public function sign(Request $request): JsonResponse
    {
        $data = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'content_type' => ['required', 'string', 'max:255'],
            'size' => ['required', 'integer', 'min:1'],
            'collection' => ['required', 'string', 'max:255'],
            'fileable_type' => ['nullable', 'string', 'max:255'],
            'fileable_id' => ['nullable', 'string', 'max:255'],
        ]);

        $fileable = $this->resolveFileable($data);

        return response()->json($this->files->sign(
            $this->collectionFor($data['collection'], $fileable),
            $data['name'],
            $data['content_type'],
            (int) $data['size'],
        ));
    }

    /**
     * The `driver=local` stand-in for a direct PUT to the object store.
     *
     * Same shape as the signed URL from the browser's point of view: raw body,
     * one request, no form. That is what lets development and production share
     * a single upload path in the client.
     */
    public function upload(Request $request, string $key): JsonResponse
    {
        abort_unless($this->files->driver() === 'local', 404);

        // The key is generated by `sign()` and echoed back here. Anything that
        // is not a plain uuid could otherwise name a path of the caller's
        // choosing on a disk they do not own.
        abort_unless(Str::isUuid($key), 422);

        $this->files->disk()->put(
            FileStore::TMP_PREFIX.'/'.$key,
            $request->getContent(),
        );

        return response()->json(['key' => FileStore::TMP_PREFIX.'/'.$key]);
    }

    public function finalize(Request $request): JsonResponse
    {
        $data = $request->validate([
            'key' => ['required', 'string', 'max:1024'],
            'name' => ['required', 'string', 'max:255'],
            'collection' => ['required', 'string', 'max:255'],
            'fileable_type' => ['nullable', 'string', 'max:255'],
            'fileable_id' => ['nullable', 'string', 'max:255'],
            'properties' => ['nullable', 'array'],
        ]);

        $fileable = $this->resolveFileable($data);

        $file = $this->files->finalize(
            key: $data['key'],
            collection: $this->collectionFor($data['collection'], $fileable),
            name: $data['name'],
            fileable: $fileable,
            properties: $data['properties'] ?? [],
            uploadedBy: Auth::id(),
        );

        return response()->json([
            'id' => $file->getKey(),
            'name' => $file->name,
            'size' => $file->size,
            'mime_type' => $file->mime_type,
            'url' => $file->url(),
        ], 201);
    }

    /**
     * Stream a file to whoever is allowed to see it.
     *
     * Used when the disk cannot sign a URL, and as the download link
     * everywhere: it re-checks on every request rather than handing out a link
     * that outlives the permission behind it.
     */
    public function show(Request $request, string $file): StreamedResponse
    {
        $model = File::query()->findOrFail($file);

        $this->authorizeAccess($model);

        $path = $model->path;

        if ($variant = $request->query('variant')) {
            $path = $model->variants[$variant] ?? abort(404);
        }

        abort_unless($model->storage()->exists($path), 404);

        return $model->storage()->response($path, $model->name, [
            'Content-Type' => $model->mime_type,
        ]);
    }

    public function destroy(string $file): JsonResponse
    {
        $model = File::query()->findOrFail($file);

        $this->authorizeAccess($model);

        $this->files->delete($model);

        return response()->json(status: 204);
    }

    /**
     * The rules of a collection come from the model that owns it, or from the
     * account-wide library when nothing owns it.
     */
    protected function collectionFor(string $name, ?Model $fileable): FileCollection
    {
        if ($fileable && method_exists($fileable, 'fileCollection')) {
            return $fileable->fileCollection($name);
        }

        $declared = config('base-tenant.files.collections', []);

        abort_unless(array_key_exists($name, $declared), 422, "Unknown file collection `{$name}`.");

        $rules = $declared[$name];

        return $rules instanceof FileCollection ? $rules : FileCollection::make(
            name: $name,
            accepts: $rules['accepts'] ?? [],
            maxSize: $rules['max_size'] ?? null,
            single: $rules['single'] ?? false,
            variants: $rules['variants'] ?? [],
        );
    }

    /**
     * @param  array<string, mixed>  $data
     */
    protected function resolveFileable(array $data): ?Model
    {
        if (empty($data['fileable_type']) || empty($data['fileable_id'])) {
            return null;
        }

        // Through the morph map, so a request names an alias the application
        // registered and not an arbitrary class to instantiate.
        $class = Model::getActualClassNameForMorph($data['fileable_type']);

        abort_unless(class_exists($class), 422, 'Unknown owner type.');

        /** @var Model $model */
        $model = (new $class)->newQuery()->findOrFail($data['fileable_id']);

        // The owner is only usable if it belongs to the account in context.
        // Without this, a valid id from another tenant would attach a file to
        // a record the caller cannot see.
        if (property_exists($model, 'account_id') || $model->getAttribute('account_id') !== null) {
            abort_unless($model->getAttribute('account_id') === Tenant::currentId(), 403);
        }

        return $model;
    }

    protected function authorizeAccess(File $file): void
    {
        // The tenant scope already keeps another account's files out of the
        // query; this covers the console and superadmin paths, where the scope
        // stands down.
        abort_unless($file->account_id === Tenant::currentId() || Auth::user()?->isSuperAdmin(), 403);
    }
}
